### ISSUE TITLE
Design Question when using SqlServer

### ISSUE THREAD

**Issue by CzechsMix** [rebus-org/Rebus.SignalR#5]
If I'm using Rebus on SqlServer for my SignalR backplane, and I plan on having multiple apps that use SignalR, should each app use the same SignalR backplane database/schema, or should the backplane use each app's SqlServer database/schema?

What are the potential hangups and drawbacks?

**Comment by rsivanov** [comment]
Hi

I personally would use separate database/schemas for multiple apps. The main reason is that you can scale your apps database resources (processing power, memory, etc.) differently, according to their load. Another reason is that in this case you could have ACID transactions with Rebus and some business logic in your code using the same database.

But if you have different databases on a single SqlServer cluster and don't have any high load requirements, for the maintenance simplicity you can just share one database for Rebus.SqlServer transport. No ACID transactions in that scenario, though :)
